### ISSUE TITLE
Problem viewing RecyclerView in CustomAdapterCredit

### ISSUE THREAD

**Issue by Fast0n** [Fast0n/iliad#1]
` java.lang.IllegalStateException:  android.support.v7.widget.RecyclerView{29138a6b VFED.... ......ID 0,0-1080,1378 #7f0800b5 app:id/recycler_view}, adapter:com.fast0n.iliad.fragments.CreditRoamingFragment.CustomAdapterCreditRoaming@2b40b9c8, layout:android.support.v7.widget.LinearLayoutManager@1bda3a61, context:com.fast0n.iliad.HomeActivity@cb4f696
        at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2779)
        at android.support.v7.widget.RecyclerView$LayoutManager.assertNotInLayoutOrScroll(RecyclerView.java:7523)
        at android.support.v7.widget.LinearLayoutManager.assertNotInLayoutOrScroll(LinearLayoutManager.java:1352)
        at android.support.v7.widget.RecyclerView.removeItemDecoration(RecyclerView.java:1566)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView.setHasMoreItems(PullToRefreshRecyclerView.java:334)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView.access$800(PullToRefreshRecyclerView.java:22)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView$InterOnScrollListener.onScrolled(PullToRefreshRecyclerView.java:389)
        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4844)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3909)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
    	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java
06-07 15:30:19.905 22149-22149/com.fast0n.iliad W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
    java.lang.IllegalStateException:  android.support.v7.widget.RecyclerView{20df476a VFED.... ......ID 0,0-1080,1378 #7f0800b5 app:id/recycler_view}, adapter:com.fast0n.iliad.fragments.CreditFragment.CustomAdapterCredit@2ccfe45b, layout:android.support.v7.widget.LinearLayoutManager@257a24f8, context:com.fast0n.iliad.HomeActivity@cb4f696
        at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2779)
        at android.support.v7.widget.RecyclerView$LayoutManager.assertNotInLayoutOrScroll(RecyclerView.java:7523)
        at android.support.v7.widget.LinearLayoutManager.assertNotInLayoutOrScroll(LinearLayoutManager.java:1352)
        at android.support.v7.widget.RecyclerView.removeItemDecoration(RecyclerView.java:1566)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView.setHasMoreItems(PullToRefreshRecyclerView.java:334)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView.access$800(PullToRefreshRecyclerView.java:22)
        at com.lhh.ptrrv.library.PullToRefreshRecyclerView$InterOnScrollListener.onScrolled(PullToRefreshRecyclerView.java:389)
        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4844)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3909)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
    	at andr
`

**Comment by Fast0n** [comment]
Fixed the problem by deleting the @HomHomLin library
