### ISSUE TITLE
Home widget volley OutOfMemoryError 

### ISSUE THREAD

**Issue by Fast0n** [Fast0n/iliad#8]
```
06-19 12:34:46.414 12663-12663/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fast0n.ipersonalarea, PID: 12663
    java.lang.OutOfMemoryError: Could not allocate JNI Env: Failed anonymous mmap(0x0, 8192, 0x3, 0x2, 44, 0): Operation not permitted. See process maps in the log.
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at com.android.volley.RequestQueue.start(RequestQueue.java:128)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:91)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:67)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:102)
        at com.fast0n.ipersonalarea.Widget.loading(Widget.java:118)
        at com.fast0n.ipersonalarea.Widget.onUpdate(Widget.java:104)
        at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3188)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Fast0n** [comment]
`android:hardwareAccelerated="false"`

**Comment by Fast0n** [comment]
> UPDATE

`android:hardwareAccelerated="false"`

```
06-22 16:49:52.209 18306-18306/com.fast0n.ipersonalarea E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fast0n.ipersonalarea, PID: 18306
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:1063)
        at com.android.volley.RequestQueue.start(RequestQueue.java:135)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:91)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:67)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:102)
        at com.fast0n.ipersonalarea.Widget.lambda$loading$2$Widget(Widget.java:152)
        at com.fast0n.ipersonalarea.Widget$$Lambda$0.onResponse(Unknown Source)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:83)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Fast0n** [comment]
https://stackoverflow.com/a/35718419


```
private RequestQueue requestQueue;

public void uploadData(String s) {
if (requestQueue == null) {
        requestQueue = Volley.newRequestQueue(context);
        Build.logError("Setting a new request queue");
    } more request stuff....
}
```

**Comment by Fast0n** [comment]
Corretto usando un Handler di 1 min
